# Generated by Django 2.0.7 on 2018-07-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_name', models.CharField(max_length=200)),
                ('cpu_price', models.CharField(max_length=20)),
            ],
        ),
    ]
