# Generated by Django 2.0.7 on 2018-07-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCPal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='cpu_speed',
            field=models.CharField(default='def val', max_length=200),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_price',
            field=models.CharField(max_length=200),
        ),
    ]
