# Generated by Django 2.0.7 on 2018-07-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCPal', '0002_auto_20180711_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='cpu_cores',
            field=models.CharField(default='def val', max_length=200),
        ),
    ]
