# Generated by Django 2.0.7 on 2018-07-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCPal', '0003_cpu_cpu_cores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='cpu_cores',
        ),
    ]
