# Generated by Django 2.0.7 on 2018-07-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCPal', '0005_mobo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_name', models.CharField(max_length=200)),
                ('ram_price', models.CharField(max_length=200)),
                ('ram_size', models.CharField(max_length=200)),
            ],
        ),
    ]
