# Generated by Django 2.0.7 on 2018-07-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCPal', '0006_ram'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_name', models.CharField(max_length=200)),
                ('gpu_price', models.CharField(max_length=200)),
                ('gpu_ram', models.CharField(max_length=200)),
            ],
        ),
    ]
