# Generated by Django 2.0.7 on 2018-07-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCPal', '0007_gpu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GPU',
        ),
    ]
